version: "3.8"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: ["redis-server"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=pmove

  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MONGO_URI_RATP=${MONGO_URI_RATP}
      - MONGO_URI_SNCF=${MONGO_URI_SNCF}
      - MONGO_URI_AIRFRANCE=${MONGO_URI_AIRFRANCE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - mongodb
